language: go
go:
  - stable
  - tip

git:
  symlinks: true

jobs:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      script:
        - make test
        - make testacc
        - make vet
    - os: osx
      script:
        - make test
        - make testacc
    - os: windows
      script:
        - TF_ACC=1 go test -v ./...
      before_script:
        - curl -fSL "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_windows_amd64.zip" -o terraform.zip
        - unzip terraform.zip -d /c/Users/travis/bin

env:
  - GO111MODULE=on GOFLAGS=-mod=vendor TF_VERSION=0.13.3

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh

branches:
  only:
  - master
